### PR TITLE
fix: related courses style issue

### LINKED ISSUE #363: [Course Migration Sub-issue 9/25] "Related Courses" is missing
**Parent Issue:** #346

**Issue:** "Related Courses" is missing

**Affected URLs:**
- https://www.cmegroup.com/education/courses/building-a-trade-plan.html
- https://main--www--cmegroup.aem.page/education/courses/building-a-trade-plan

Image

Image

### PR DESCRIPTION
**Pull request by nawaz-adobe**
Fix #363 

Test URLs:
- Before: https://main--www--cmegroup.aem.live/education/courses/building-a-trade-plan
- After: https://issue-363--www--cmegroup.aem.live/education/courses/building-a-trade-plan

### CODE REVIEW

File: aemedge/blocks/cards/cards.js [hunk 1]
```diff
@@ -325,16 +326,17 @@ async function fetchAndFilterUpcomingEconodayEvent() {
 
 export async function createDynamicCards(block, numEntries = null) {
   const config = readBlockConfig(block);
+  const tags = getMetadata('article:tag');
+  const tagsArray = tags ? tags.split(',').map((tag) => tag.trim().toLowerCase()) : [];
```
Comment (ndedios) [inline aemedge/blocks/cards/cards.js:330]: if tags coming from the current page are required for a variation, please move this to the specific section in the code.
Please verify if "course" variation is being used in another page where tags comes from block metadata. If yes, you could add a variation like (course, related) to indicate where the tags will come from

**Review by ndedios — CHANGES_REQUESTED** [review]

**Comment by ndedios** [comment]
@nawaz-adobe @kunwarsaluja to reach the search API requires the access to https://beta.cmegroup.com , we use a VPN to do that, not sure if the adobe team is able to reach that domain

File: aemedge/blocks/cards/cards-related-courses.css
Comment (ndedios) [inline aemedge/blocks/cards/cards-related-courses.css:1]: Please update this css file to follow the guidelines defined at:

https://adobe-dx-support.slack.com/archives/C06PK80B5A5/p1750794951061859

(mostly the usage of nesting classes, rem instead of px and media queries fixes)

**Review by ndedios — CHANGES_REQUESTED** [review]

File: aemedge/blocks/cards/cards-related-courses.css
Comment (nawaz-adobe) [reply aemedge/blocks/cards/cards-related-courses.css:1]: done

File: aemedge/blocks/cards/cards-related-courses.css [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+.cards.related-courses ul {
+    grid-template-columns: repeat(3, 1fr);
+}
+
+.cards.related-courses .cards-card-body img {
+    object-fit: cover;
+    height: 100%;
+    width: 100%;
+}
```
Comment (ndedios) [inline aemedge/blocks/cards/cards-related-courses.css:25]: Please use nesting classes in the whole file, like 
```
.cards.related-courses {
  & ul {
    grid-template-columns: repeat(3, 1fr);

    & .cards-card-body {
      & img {
        ....
```

File: aemedge/blocks/cards/cards-related-courses.css [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+
+@media (width >= 993px) {
+    .cards.related-courses .cards-card {
```
[the remark this answers is not in the document]
Comment (nawaz-adobe) [reply aemedge/blocks/cards/cards-related-courses.css]: updated.. i hope i got it right this time :D

**Review by kunwarsaluja — APPROVED** [review]
