### PR TITLE
Fix# 147 Section Parallax

### LINKED ISSUE #147: Section Variant - Parallax effect and background image
Section Variant - Parallax effect and background image
Sample page - https://www.cmegroup.com/education/articles-and-reports/cme-fx-futures-new-ticks-on-the-blocks.html

Image

### PR DESCRIPTION
**Pull request by jfait**
Fix #147  Section Parallax

Before: https://main--www--cmegroup.aem.live/drafts/john/issue-147-parallax-section
After: https://issue-147-sectionParallax--www--cmegroup.aem.live/drafts/john/issue-147-parallax-section

### CODE REVIEW

File: aemedge/scripts/scripts.js [hunk 1]
```diff
@@ -141,6 +141,24 @@ function decorateSections(main) {
...
+function initParallaxSections(main) {
+  const parallaxSections = main.querySelectorAll('.section.parallax[data-background-image]:not([data-parallax-processed])');
+
+  parallaxSections.forEach((section) => {
+    const { backgroundImage } = section.dataset;
+    if (backgroundImage) {
+      section.style.backgroundImage = `url('${backgroundImage}')`;
+      // Clean up the data attribute and mark as processed
+      delete section.dataset.backgroundImage;
+      section.dataset.parallaxProcessed = 'true';
```
Comment (jindaliiita) [inline aemedge/scripts/scripts.js:157]: what is the need of this parallaxProcessed ?

**Review by jindaliiita — APPROVED** [review]

**Review by jindaliiita — APPROVED** [review]
